// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqQAInRZtWBNrRWua5qn2IX5lZ-lGWyQU',
    appId: '1:962604690676:web:d9d1ea1e9d0f80959682a1',
    messagingSenderId: '962604690676',
    projectId: 'bmart',
    authDomain: 'bmart.firebaseapp.com',
    storageBucket: 'bmart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnJ1cM03XtZZzo-ujfQG2RWNmMuW4z-VA',
    appId: '1:962604690676:android:247bac6c868305d79682a1',
    messagingSenderId: '962604690676',
    projectId: 'bmart',
    storageBucket: 'bmart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaXB4i21wJgwyBnxi5W03pDgDKnZbX7Os',
    appId: '1:962604690676:ios:9a76f41c9574c1079682a1',
    messagingSenderId: '962604690676',
    projectId: 'bmart',
    storageBucket: 'bmart.appspot.com',
    iosClientId:
        '962604690676-cvq9sltjjsfbdqcsun6v9i8i4oqrpds9.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.bmart',
  );
}
