// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY-ezVaIQoV-lya3iQD7-f1A3s2uVYyD0',
    appId: '1:818542515734:web:a759f8073344af71388737',
    messagingSenderId: '818542515734',
    projectId: 'bmart-28fe5',
    authDomain: 'bmart-28fe5.firebaseapp.com',
    storageBucket: 'bmart-28fe5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxxzXjUrhx2Zd9A5egunRVpci-WGruFjc',
    appId: '1:818542515734:android:2830a85bb5ad1690388737',
    messagingSenderId: '818542515734',
    projectId: 'bmart-28fe5',
    storageBucket: 'bmart-28fe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP3CZVexvTMFQxR6-jXG0doHGZwmFzKM4',
    appId: '1:818542515734:ios:67ca28d871fef615388737',
    messagingSenderId: '818542515734',
    projectId: 'bmart-28fe5',
    storageBucket: 'bmart-28fe5.appspot.com',
    iosClientId: '818542515734-8kdc3ice4r1t6aev3r9qimrklionm56c.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.bmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP3CZVexvTMFQxR6-jXG0doHGZwmFzKM4',
    appId: '1:818542515734:ios:397e7140fe701b82388737',
    messagingSenderId: '818542515734',
    projectId: 'bmart-28fe5',
    storageBucket: 'bmart-28fe5.appspot.com',
    iosClientId: '818542515734-ndvusbupptg85tplivc3biibt8b2g2j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmart',
  );
}
